apiVersion: v2
name: testapp
description: A test chart
type: application

version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: cassandra
    repository: https://charts.bitnami.com/bitnami
    version: 7.0.1
