image:
  reg: ghcr.io
  repo: benc-uk/java-cassandra-test
  tag: latest

replicas: 1

network:
  port: 8080
service:
  port: 80
  type: ClusterIP
ingress:
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

cassandra:
  persistence:
    enabled: true
  replicaCount: 1
  cluster:
    datacenter: datacenter1 # No effect due to this bug https://github.com/bitnami/charts/issues/4408
  dbUser:
    user: cassandra
  initDBConfigMap: testapp-cassandra-db-init

prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  extraScrapeConfigs: |
    - job_name: app_metrics
      kubernetes_sd_configs:
      - role: service
        selectors:
        - role: service
          label: "app.kubernetes.io/name=testapp"

grafana:
  service:
    type: LoadBalancer
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
