apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "testapp.selectorLabels" . | nindent 6 }}
  
  template:
    metadata:
      labels:
        {{- include "testapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: testapp
        image: {{ .Values.image.reg }}/{{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: Always

        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"

        ports:
        - containerPort: {{ .Values.network.port }}

        env:
          - name: CASSANDRA_CLUSTER
            value: {{ .Release.Name }}-cassandra-headless
          - name: CASSANDRA_KEYSPACE
            value: k1
          - name: CASSANDRA_USERNAME
            value: cassandra
          - name: CASSANDRA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-cassandra
                key: cassandra-password
          - name: PORT
            value: "{{ .Values.network.port }}"

        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.network.port }}
        readinessProbe:
          httpGet:
            path: /status
            port: {{ .Values.network.port }}