kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "testapp.fullname" . }}
data:
  application.properties: |-
    quarkus.http.port={{ .Values.network.port }}
    quarkus.cassandra.contact-points={{ .Release.Name }}-cassandra-headless:9042
    quarkus.cassandra.auth.username={{ .Values.cassandra.dbUser.user }}
    quarkus.cassandra.auth.password={{ .Values.cassandra.dbUser.password }}
    quarkus.cassandra.local-datacenter={{ .Values.cassandra.cluster.datacenter }}
