cassandra:
  replicaCount: 2
  persistence:
    enabled: false

prometheus:
  server:
    persistentVolume:
      enabled: false

replicas: 8

ingress:
  enabled: true
  hosts:
    - host: testapp.kube.benco.io
      paths: ["/"]
  tls:
    - secretName: kube-benco-io-cert
      hosts:
        - testapp.kube.benco.io

grafana:
  ingress:
    enabled: true
    hosts: ["grafana.kube.benco.io"]
    tls:
      - secretName: kube-benco-io-cert
        hosts:
          - grafana.kube.benco.io
