prometheus:
  server:
    persistentVolume:
      enabled: false

grafana:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts: ["grafana.kube.benco.io"]
    tls:
      - secretName: temp-cert # kube-benco-io-cert
        hosts:
          - grafana.kube.benco.io
